# Generated by Django 5.2.5 on 2025-08-15 17:58

import my_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_utilisateur_sexe'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='utilisateur',
            managers=[
                ('objects', my_app.models.UtilisateurManager()),
            ],
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(blank=True, choices=[('administrateur', 'Administrateur'), ('responsable', 'Responsable')], max_length=20, null=True),
        ),
    ]
