# Generated by Django 5.1.1 on 2026-05-16 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0004_classe_eleve"),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matiere", models.CharField(max_length=100)),
                ("valeur", models.DecimalField(decimal_places=2, max_digits=5)),
                ("date_evaluation", models.DateField()),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="my_app.eleve",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Paiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_paiement", models.DateField(auto_now_add=True)),
                (
                    "type_paiement",
                    models.CharField(
                        choices=[
                            ("frais_inscription", "Frais d'inscription"),
                            ("ecolage", "Écolage"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("commentaire", models.TextField(blank=True, null=True)),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paiements",
                        to="my_app.eleve",
                    ),
                ),
            ],
        ),
    ]
